name = "NaturalNeighborsInterpolation"
uuid = "68cdaad2-3999-4583-aeed-dd629d2fb15f"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
VoronoiCells = "e3e34ffb-84e9-5012-9490-92c94d0c60a4"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"
